app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_admin:
    resource: routing/admin.yml
    prefix: /admin

#_user:
#    resource: routing/user.yml
#    prefix: /user
#
#_api:
#    resource: routing/api.yml
#    prefix: /api
